name: endpoints

services:
  db:
    image: postgres:16.14-alpine
    env_file: .env
    volumes:
      # - ./endpoints.sql:/docker-entrypoint-initdb.d/endpoints.sql
      - endpoints-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8.6.3-alpine
    restart: unless-stopped

  service:
    build: .
    ports:
      - 3001:8080
    restart: unless-stopped
    depends_on:
      - db

volumes:
  endpoints-data:
    name: endpoints-data
