version: '3'

services:
  postgres:
    image: "postgres:10.2-alpine"
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: endpoint
      POSTGRES_USER: endpoint_user
      POSTGRES_PASSWORD: ue
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"

  endpoint-service:
    build: .
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  pgdata:
